In [4]:
def fnmain():
    x,y =8,7
    if(x < y):
        return x
    else:
        return y

fnmain()

7

In [9]:
for val in [10,20,25,45,60] :
    if val>25:
        break
    print(val)


10
20
25


In [12]:
###numpy
import numpy as np
np.sqrt(16)

4.0

In [16]:
#ceil fn -next whole no 
np.ceil(15.17)

16.0

In [18]:
np.array([5,7,8])

array([5, 7, 8])

In [19]:
#to get the total no of elements in the list
mat=np.array([1,4,4,7,9,16,8])
mat.size

7

In [22]:
#to get the no of rows and col -shape fn
mat.shape

(7,)

In [26]:
#arange fn
#range([start,] stop[, step,], dtype=None, *, like=None)

a=np.arange(2,12,2)
a

array([ 2,  4,  6,  8, 10])

In [33]:
#reversing the array
a[2:12:-2]
a

array([ 2,  4,  6,  8, 10])

In [39]:
#linearly spaced nos 
#Linspace(start,stop,no of elements)
a=np.linspace(10,40,16)
a

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38., 40.])

In [44]:
#matrix with zeroes
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [48]:
print(np.ones((5,8)))

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
