In [1]:
import numpy as np

In [2]:
np.square(16)

256

In [3]:
xyz=np.array([5,7,8,9])

xyz

array([5, 7, 8, 9])

In [4]:
#to know abot total no of elements in array "size"
xyz.size

4

In [5]:
xyz.shape

(4,)

In [6]:
#range functinon
a=np.arange(1,10,0.4)
a


array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. , 5.4, 5.8,
       6.2, 6.6, 7. , 7.4, 7.8, 8.2, 8.6, 9. , 9.4, 9.8])

In [7]:
#reversing the created array
a[ : : -1]

array([9.8, 9.4, 9. , 8.6, 8.2, 7.8, 7.4, 7. , 6.6, 6.2, 5.8, 5.4, 5. ,
       4.6, 4.2, 3.8, 3.4, 3. , 2.6, 2.2, 1.8, 1.4, 1. ])

In [8]:
a[ : : -2]

array([9.8, 9. , 8.2, 7.4, 6.6, 5.8, 5. , 4.2, 3.4, 2.6, 1.8, 1. ])

In [9]:
np.linspace(20,50,4)


array([20., 30., 40., 50.])

In [10]:
np.linspace(20,50,20)


array([20.        , 21.57894737, 23.15789474, 24.73684211, 26.31578947,
       27.89473684, 29.47368421, 31.05263158, 32.63157895, 34.21052632,
       35.78947368, 37.36842105, 38.94736842, 40.52631579, 42.10526316,
       43.68421053, 45.26315789, 46.84210526, 48.42105263, 50.        ])

In [11]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [12]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [13]:
x=np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Random no generation

In [14]:
#np.random.randint(1,100,(5,4))
#                (start,end,(row,col))#shape 
np.random.randint(1,100,(5,4))

array([[21, 57,  8,  1],
       [58, 80, 18, 47],
       [61,  5, 78, 53],
       [51,  3, 73, 43],
       [95, 13, 40, 54]])

In [15]:
#np.random.rand(10,5)
#                (row,col)
np.random.rand(10,5)

array([[0.57863592, 0.7403492 , 0.37477493, 0.54986386, 0.31213967],
       [0.84474037, 0.65384681, 0.01957941, 0.52693708, 0.51953823],
       [0.87028638, 0.21020562, 0.0927456 , 0.61009384, 0.49934674],
       [0.14918209, 0.15263338, 0.60033127, 0.51858317, 0.09244215],
       [0.20528166, 0.75487315, 0.56576608, 0.43664341, 0.88481791],
       [0.60548518, 0.07782746, 0.23784173, 0.12693405, 0.9524913 ],
       [0.11216682, 0.99006367, 0.23102272, 0.58303495, 0.64082646],
       [0.9127931 , 0.74534054, 0.22297296, 0.5019886 , 0.53081758],
       [0.75571714, 0.08126349, 0.75470185, 0.66817874, 0.32670928],
       [0.59444401, 0.08940222, 0.61774137, 0.40548093, 0.4494208 ]])

In [16]:
np.random.rand(5)

array([0.19510719, 0.56148794, 0.05906117, 0.95571959, 0.97718968])

# to set max and min values inside the random nos generated

In [17]:
mat=np.array(ri(10,100,15).reshape(3,5))
mat

NameError: name 'ri' is not defined

In [18]:
mat>50

NameError: name 'mat' is not defined

In [ ]:
print(mat[mat>50])

In [ ]:
print(np.where(mat==65))

In [ ]:
x=np.random.randint(8,70,(10))
x

In [ ]:
y=np.random.randint(8,70,10)
np.clip(x,a_min=20,a_max=50)

# where fn-used to get the index of the condt matched


In [19]:
age=70
np.where(age>68,'retired','still_walking')

array('retired', dtype='<U13')

In [20]:
y=np.random.randint(8,70,10)
y

array([21, 45, 41, 64, 28, 67, 65, 63, 45, 27])

In [21]:
np.where(y<35)

(array([0, 4, 9], dtype=int64),)

In [22]:
from  numpy.random import randint as ri


In [23]:
a=ri(1,199,30)
a

array([ 68,  59, 187, 114, 133,  67,   3,  91, 151, 171, 137, 183, 116,
       187, 170,  55, 179, 183,  78,   6, 180, 119, 180,  19, 158, 152,
        45, 189,   6,  76])

In [24]:
b=a.reshape(10,3)
b

array([[ 68,  59, 187],
       [114, 133,  67],
       [  3,  91, 151],
       [171, 137, 183],
       [116, 187, 170],
       [ 55, 179, 183],
       [ 78,   6, 180],
       [119, 180,  19],
       [158, 152,  45],
       [189,   6,  76]])

In [25]:
print(b.min())

3


In [26]:
print(b.max())

189


In [27]:
print(b.sum())

3462


In [28]:
print(b.mean())

115.4


In [44]:
arr=np.arange(0,21,2)
            #(start,end,skip_size)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [45]:
print(arr[::-1])

[20 18 16 14 12 10  8  6  4  2  0]


In [31]:
#to know the index positions of the values
print(arr[[0,1,2]])

[0 2 4]


In [32]:
mat1=[[1,2,3],[4,5,6],[7,8,9]]
mat1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [49]:
mat2=np.array(mat1)
mat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
print(mat2[0:2,1:2])

[[2]
 [5]]


In [35]:
#mat[rows,[col indexes]]
print(mat2[0:2,[0,2]])


[[1 3]
 [4 6]]


In [51]:
print(mat2[0:2,[2]])

[[3]
 [6]]


In [50]:
print(mat2[0:2,2])

[3 6]


In [37]:
print(mat2[0:2,[0]])

[[1]
 [4]]


In [38]:
#updating the value of matrix
mat2[0,2]=34
mat2

array([[ 1,  2, 34],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [39]:
add_rows=np.array([1,0,2])
add_rows

array([1, 0, 2])

In [40]:
#transposing a matrix
transp=add_rows.T
transp


array([1, 0, 2])

In [41]:
z=[25,30,45,76,78,67]
print(max(z))

78


In [42]:
np.amin([25,30,45,76,78,67])

25

In [43]:
np.amax([25,30,45,76,78,67])

78